import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full max-w-9/10 mx-auto`}
      >
        <div className="">
          <header className="flex items-end justify-between border-b-2">
            <Link href={"/"} className="text-8xl">
              Jawort
            </Link>
            <Link href={"/auth/login"}>ログイン</Link>
          </header>
          <main>
            <div className="divide-x-2 text-center m-5">
              <Link href={"/invitation"} className="px-2">
                オンライン招待状の作成
              </Link>
              <Link href={"/search_chapel"} className="px-2">
                式場を探す
              </Link>
              <Link href={"/guide"} className="px-2">
                使い方ガイド
              </Link>
            </div>
          </main>
        </div>
        {children}
      </body>
    </html>
  );
}
